<?php
/**
 * @file
 * dkan_sci_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function dkan_sci_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-LeKDPflArwbla6ejaP5WRlVMKEnP2jW8'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'LeKDPflArwbla6ejaP5WRlVMKEnP2jW8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-QgYbgFm8oSoxQv1YKeZjlahVgXX5Z6kK'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'QgYbgFm8oSoxQv1YKeZjlahVgXX5Z6kK',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-S1UOZGxHcdgLDtZaE4EL8f74GzrzoY3q'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'S1UOZGxHcdgLDtZaE4EL8f74GzrzoY3q',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-W8zNmAfGcDv9PHup7hV360kOJUcAN8MX'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'W8zNmAfGcDv9PHup7hV360kOJUcAN8MX',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-XqPO2VhjVQge73r6F1jfMBlm1t1Dz4E1'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'XqPO2VhjVQge73r6F1jfMBlm1t1Dz4E1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-aHfXVeMRImNbarH00aqILB20kpCfO6gU'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'aHfXVeMRImNbarH00aqILB20kpCfO6gU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-bfw0tqJwZnrMbJ7WJ2MIh322HZssSUED'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'bfw0tqJwZnrMbJ7WJ2MIh322HZssSUED',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-fW7nO9zfJJdVSfIrHovvto8cPDt857bs'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fW7nO9zfJJdVSfIrHovvto8cPDt857bs',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-fgJd3L6zhrCtitSOlWH7kb2eqHjjZmc6'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'fgJd3L6zhrCtitSOlWH7kb2eqHjjZmc6',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-w17OPm7ydu8xzFN0LKLUKq2wquFas6G0'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'w17OPm7ydu8xzFN0LKLUKq2wquFas6G0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-xA0C1xk10oQYi5nZZeyAyqOvjpn5AmsT'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'xA0C1xk10oQYi5nZZeyAyqOvjpn5AmsT',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zzisZMGGR0R4x7GT1t5dgYr6o4TxahQ4'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'zzisZMGGR0R4x7GT1t5dgYr6o4TxahQ4',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-dkan_sci_search-block'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'dkan_sci_search-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'nuboot_radix' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'nuboot_radix',
        'weight' => 0,
      ),
      'usda_radix_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'usda_radix_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
